import { StyleSheet } from 'react-native';

export const getModalColors = (modalType) => {
    switch (modalType) {
        case 'success': return { bg: 'rgb(165, 220, 134)', bgOpacity: 'rgba(165, 220, 134, 0.1)' };
        case 'warning': return { bg: 'rgb(250, 206, 168)', bgOpacity: 'rgba(250, 206, 168, 0.1)' };
        default: return { bg: 'rgb(242, 116, 116)', bgOpacity: 'rgba(242, 116, 116, 0.1)' };
    }
};

const styles = StyleSheet.create({
    category: {
        backgroundColor: '#FFFFFF',
        paddingVertical: 20,
        paddingHorizontal: 10,
        borderRadius: 8,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    categoryName: {
        display: 'flex',
        flex: 1,
        fontSize: 18,
        fontFamily: 'PoppinsMedium',
        color: '#495057',
        lineHeight: 20,
    },
    dishCategoryName: {
        display: 'flex',
        fontSize: 13,
        fontFamily: 'PoppinsRegular',
        color: '#FF9900',
    },
    dishButton: {
        backgroundColor: '#EDEDED',
        paddingVertical: 5,
        paddingHorizontal: 10,
        borderRadius: 5,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    // Modal actions
    modalActionContainer: {
        flex: 1,
        backgroundColor:'red',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
    },
    modalContent: {
        width: '90%',
        borderTopWidth: 5,
        borderTopColor: '#FF9900',
        backgroundColor: '#FFFFFF',
        paddingVertical: 20,
        paddingHorizontal: 20,
        alignItems: 'center',
    },
    modalHeader: {
        width: '100%',
        alignItems: 'flex-end',
        paddingHorizontal: 20,
        marginBottom: 10,
    },
    close: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#FF9900',
        justifyContent: 'center',
        alignItems: 'center',
    },
    actions: {
        marginTop: 12,
        flexDirection: 'row',
    },
    actionsItemEdit: {
        flex: 1,
        backgroundColor: '#EDEDED',
        padding: 10,
        borderRadius: 4,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginHorizontal: 5,
    },
    actionsItemDelete: {
        flex: 1,
        backgroundColor: 'rgb(242, 116, 116)',
        padding: 10,
        borderRadius: 4,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginHorizontal: 5,
    },
    deleteActionItemEdit: {
        backgroundColor: '#F9F9F9',
        paddingVertical: 10,
        paddingHorizontal: 15,
        borderRadius: 4,
        justifyContent: 'center',
        alignItems: 'center',
        marginHorizontal: 5,
    },
    deleteActionItemDelete: {
        backgroundColor: 'rgb(242, 116, 116)',
        paddingVertical: 10,
        paddingHorizontal: 15,
        borderRadius: 4,
        justifyContent: 'center',
        alignItems: 'center',
        marginHorizontal: 5,
    },
    editActionItem: {
        width: '100%',
        backgroundColor: '#FF9900',
        paddingVertical: 10,
        paddingHorizontal: 15,
        borderRadius: 4,
        justifyContent: 'center',
        alignItems: 'center',
        marginHorizontal: 5,
    },
    checkbox: {
        width: 20,
        height: 20,
        borderWidth: 1,
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
        borderRadius: 2,
    },
    inputArea: {
        width: '100%',
    },
    switchRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        borderRadius: 8,
        paddingHorizontal: 16,
        paddingVertical: 12,
        marginTop: 12,
        borderWidth: 1,
        borderColor: '#E0E0E0',
    },
    switchItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    switchLabel: {
        fontSize: 16,
        color: '#333333',
        fontFamily: 'PoppinsMedium',
    },
    label: {
        fontSize: 16,
        color: '#495057',
        marginBottom: 10,
        fontFamily: 'PoppinsMedium',
    },
    input: {
        borderWidth: 1,
        borderColor: '#DDDDDD',
        backgroundColor: '#FFFFFF',
        borderRadius: 4,
        color: '#495057',
        fontSize: 16,
        padding: 10,
        marginBottom: 20,
        fontFamily: 'PoppinsRegular',
    },
    toogleDishStatus: {
        flex: 1,
        flexDirection: 'row',
    },
    toogleDishStatusText: {
        fontSize: 16,
        color: '#AAAAAA',
        fontFamily: 'PoppinsRegular',
        marginLeft: 5,
    },
    modalActionTitle: {
        width: '100%',
        textAlign: 'center',
        fontSize: 16,
        fontFamily: 'PoppinsRegular',
        color: '#333333',
        marginBottom: 20,
    },
    modalTitleCategoryName: {
        fontFamily: 'PoppinsBold',
        color: '#FF9900',
    },
    actionTitleEdit: {
        fontSize: 16,
        color: '#AAAAAA',
        fontFamily: 'PoppinsMedium',
    },
    actionTitleDelete: {
        fontSize: 16,
        color: '#FFFFFF',
        fontFamily: 'PoppinsMedium',
    },
    // Full screen modal
    modalContainer: {
        flex: 1,
        paddingTop: 60,
        paddingHorizontal: 25,
        paddingBottom: 30,
        backgroundColor: '#FFFFFF',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    modalTitle: {
        fontFamily: 'PoppinsBold',
        fontSize: 28,
        lineHeight: 28,
        color: '#495057',
        marginBottom: 20,
    },
    circleOpacity: {
        width: 135,
        height: 135,
        borderRadius: 70,
        justifyContent: 'center',
        alignItems: 'center',
    },
    circle: {
        width: 100,
        height: 100,
        borderRadius: 50,
        justifyContent: 'center',
        alignItems: 'center',
    },
    backToHome: {
        width: '100%',
        padding: 15,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 5,
    },
    backToHomeText: {
        fontFamily: 'PoppinsBold',
        textAlign: 'center',
    },
    message: {
        fontFamily: 'PoppinsMedium',
        textAlign: 'center',
        fontSize: 18,
        color: '#AAAAAA',
    },
});

export default styles;
